### PR TITLE
Added Sphinx

### PR DESCRIPTION
**Pull request by DartingMelody**
## General Checkups
- [x] Have you checked that there aren't other open pull requests for the same issue/update/change?
- [ ] If your code includes new features and not just bug fixes/copy editing: Did you include new tests?

### CODE REVIEW

**Comment by DartingMelody** [comment]
@gedankenstuecke @mcescalante @madprime I have added sphinx documentation. The generated documentation can be hosted on github pages by hosting the docs/docs_html/html folder. Hosting is only possible by the project owners. The hound issues are in the autogenerated html files. CodeClimate issues are in the javascript files which are linked to the autogenerated files. Please review. Thanks!

**Comment by DartingMelody** [comment]
Hi @mcescalante, I have updated the dev-requirements, removed the html files, and also added a section for setting up documentation locally in the README files. Please review. Thanks! :)

**Comment by DartingMelody** [comment]
Hi @gedankenstuecke , @mcescalante, I have removed sphinx warnings. The warning due to _static was due to untracked empty folder which I fixed. Other indentation error have also been fixed. On my end, the documentation is getting build without any warnings/errors. Please review. Thanks :)

**Comment by gedankenstuecke** [comment]
Awesome, we should now set up the readthedocs integration.

**Pull request merged**
