### PR TITLE
Added functionality to upload large files from cli 

### PR DESCRIPTION
**Pull request by DartingMelody**
## General Checkups
- [x] Have you checked that there aren't other open pull requests for the same issue/update/change?
- [ ] If your code includes new features and not just bug fixes/copy editing: Did you include new tests?

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
I'm not sure whether we want to implement it this way. @madprime can you give feedback on this? E.g. should the CLI for uploading files switch to the AWS S3 upload method once the max_file_size is hit?

**Comment by DartingMelody** [comment]
@madprime , in that case shall I close this PR ??

**Comment by madprime** [comment]
@DartingMelody sure, if you'd like to drop this, that's fine (I'll let you decide).

I do think this PR had a good idea in it! It's a good idea to switch the upload function to use `upload_aws`, without this it won't work for large files :)

**Comment by DartingMelody** [comment]
Hi @madprime . I have made some changes. Please review. Thanks :)

**Comment by madprime** [comment]
Merged (finally), thank you @DartingMelody!

**Pull request merged**
