### PR TITLE
Added oauth2 token exchange functionality in command line

### PR DESCRIPTION
**Pull request by DartingMelody**
## General Checkups
- [x] Have you checked that there aren't other open pull requests for the same issue/update/change?
- [ ] If your code includes new features and not just bug fixes/copy editing: Did you include new tests?

### CODE REVIEW

**Comment by DartingMelody** [comment]
Hi @madprime , @gedankenstuecke , @mcescalante , I have added token exchange functionality to be directly used through command line. Please suggest some way to solve the codeclimate issue. Thanks :)

**Comment by DartingMelody** [comment]
@gedankenstuecke here is an example of the output 
{'expires_in': 36000, 'scope': 'wildlife write read open-humans american-gut pgp go-viral', 'token_type': 'Bearer', 'access_token': 'ACCESS_TOKEN', 'refresh_token': 'REFRESH_TOKEN'}
If any change in the format is required, I will be happy to change it!

**Comment by gedankenstuecke** [comment]
Ah, so it's a regular python dictionary that's printed? It could maybe be run through `json.dumps(dict)` to make sure it's a valid json, that might be more useful downstream. What do you think @mcescalante?

**Comment by DartingMelody** [comment]
Hi @mcescalante adding sphinx documentation to click commands requires additional modules. I have added that in my other PR [59](https://github.com/OpenHumans/open-humans-api/pull/59). Once that is merged, it will be easier for me to add the docstrings here. :)

**Comment by mcescalante** [comment]
@DartingMelody #59 is merged and I've merged master into this PR, so feel free to `git pull` and add the docstrings now!

**Comment by DartingMelody** [comment]
Hi @mcescalante , I have added the docstring please review :)

**Comment by madprime** [comment]
Works for me! I'm going to merge now, thank you @DartingMelody :smile:

**Pull request merged**
